# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=40)),
                ('unit_type', models.CharField(choices=[(b'ITEM', b'ITEM'), (b'CUP', b'CUP'), (b'TBSP', b'TBSP'), (b'TSP', b'TSP')], max_length=10)),
                ('unit_cost', models.FloatField()),
                ('amount', models.FloatField()),
                ('component_type', models.CharField(choices=[(b'R', b'RecipComp'), (b'I', b'IngredientComp')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe_book.RecipeComponent'),
        ),
    ]
