# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomponent',
            name='component_type',
            field=models.CharField(choices=[(b'R', b'RecipeComp'), (b'I', b'IngredientComp')], max_length=2),
        ),
    ]
