# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0002_auto_20180210_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomponent',
            name='directions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='unit_cost',
            field=models.FloatField(null=True),
        ),
    ]
