# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0003_auto_20180210_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomponent',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='unit_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
