# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0005_auto_20180210_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomponent',
            name='component_type',
            field=models.CharField(choices=[(b'I', b'Ingredient'), (b'R', b'Recipe')], max_length=2),
        ),
    ]
