# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0006_auto_20180210_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomponent',
            name='unit_type',
            field=models.CharField(choices=[(b'ITEM', b'ITEM'), (b'CUP', b'CUP'), (b'TBSP', b'TBSP'), (b'TSP', b'TSP'), (b'LB', b'LB'), (b'OZ', b'OZ'), (b'GRAM', b'GRAM')], max_length=10),
        ),
    ]
