# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0007_auto_20180218_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientamount',
            name='unit_type',
            field=models.CharField(choices=[(b'ITEM', b'ITEM'), (b'CUP', b'CUP'), (b'TBSP', b'TBSP'), (b'TSP', b'TSP'), (b'LB', b'LB'), (b'OZ', b'OZ'), (b'GRAM', b'GRAM')], default='ITEM', max_length=10),
            preserve_default=False,
        ),
    ]
