# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0008_ingredientamount_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomponent',
            name='cups_to_lbs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
