# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0009_recipecomponent_cups_to_lbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='unit_type',
            field=models.CharField(choices=[('ITEM', 'ITEM'), ('CUP', 'CUP'), ('TBSP', 'TBSP'), ('TSP', 'TSP'), ('LB', 'LB'), ('OZ', 'OZ'), ('GRAM', 'GRAM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='component_type',
            field=models.CharField(choices=[('R', 'Recipe'), ('I', 'Ingredient')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recipecomponent',
            name='unit_type',
            field=models.CharField(choices=[('ITEM', 'ITEM'), ('CUP', 'CUP'), ('TBSP', 'TBSP'), ('TSP', 'TSP'), ('LB', 'LB'), ('OZ', 'OZ'), ('GRAM', 'GRAM')], max_length=10),
        ),
    ]
