# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 02:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_book', '0012_auto_20180924_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebook',
            name='users',
            field=models.ManyToManyField(related_name='recipe_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
